server:
  port: 8080
  servlet:
    context-path: /supermarket
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  data:
    elasticsearch:
      cluster-name: whg
      cluster-nodes: 127.0.0.1:9300
#  rabbitmq:
#    host: localhost # rabbitmq的连接地址
#    port: 5672 # rabbitmq的连接端口号
#    virtual-host: /yuanda # rabbitmq的虚拟host
#    username: guest # rabbitmq的用户名
#    password: guest # rabbitmq的密码
#    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  redis:
    host: localhost # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  datasource:
    name: source
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: qwe159358
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern : /**
  jmx:
    enabled: false

  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html



mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    - classpath*:com/mxz/supermarket/mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true


logging:
  config: classpath:log4j2.yml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 300 # 验证码超期时间

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com    # oss对外服务的访问域名
    accessKeyId: LTAI4FmuB13XASQCCkPsypc1 # 访问身份验证中用到用户标识
    accessKeySecret: vOTVGkfVnLOx0ATiFDXEQ41HsjNw78 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: whg-yuanda    # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://28c263f897.wicp.vip/yuanda/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: supermarket/images/ # 上传文件夹路径前缀

elasticsearch:
  cluster:
    name: whg
  host: 127.0.0.1
  port: 9300